apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: intra-cluster-mtls-ca-bundle
spec:
  sources:
    - secret:
        name: ca-key-pair-0001
  target:
    namespaceSelector:
      matchLabels:
        mtls.zarvd.dev/intra-cluster-mtls: "true"
    configMap:
      key: ca-bundle.pem
      metadata:
        labels:
          app.kubernetes.io/component: "trust-bundle"
