apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: intra-cluster-mtls-ca-bundle
spec:
  sources:
    - secret:
        name: self-signed-root-ca-0001
        key: tls.crt
    - secret:
        name: self-signed-root-ca-0002
        key: tls.crt
  target:
    namespaceSelector:
      matchLabels:
        mtls.zarvd.dev/intra-cluster-mtls: "true"
    configMap:
      key: ca-bundle.pem
      metadata:
        labels:
          app.kubernetes.io/component: "trust-bundle"
