apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-certificate
  namespace: mtls-client
spec:
  duration: 1h
  renewBefore: 30m
  secretName: client-secret
  commonName: mtls-client
  dnsNames:
    - mtls-client
  usages:
    - client auth
    - digital signature
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
