name: "Build Docker Image"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag"
        required: false
        default: "latest"
        type: string
  push:
    branches:
      - master

jobs:
  build-server-image:
    name: Build mtls-demo server image
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      SERVER_IMG: ghcr.io/zarvd/mtls-demo/server:${{ inputs.tag || github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
        run: |
          SERVER_IMG=${{ env.SERVER_IMG }} make image-server
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker Image
        run: |
          docker push ${{ env.SERVER_IMG }}
